name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          context: .
          submodules: true 
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          context: .
          python-version: 3.9
      - name: Install sphinx
        run: |
          pip install sphinx
          pip install furo
          pip install sphinx-togglebutton
          pip install sphinx-favicon
          pip install sphinxcontrib.bibtex
      - name: Build  # build from docs/sphinx
        run: |
          cd docs/sphinx/
          make clean
          make html
          cp source/index_replace.html build/html/index.html
          cp source/lammps_replace.html build/html/non-tutorials/lammps.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/2024.2' }}
        with:
          context: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          enable_jekyll: false
          allow_empty_commit: true
          keep_files: false
          force_orphan: true
